### ISSUE TITLE
Fixing #80 creates a related bug

### ISSUE THREAD

**Issue by uliska** [jperon/lyluatex#141] opened 2018-02-19 13:58 UTC
6e0b20da250cd5bfc59e7db1962ff7c67ded8cff breaks most documents.

```TeX
\documentclass{scrartcl}

\usepackage{lyluatex}
\begin{document}

\lilypond{ c' }

\end{document}
```
Causes this error:

```
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))[\directlua]:1:
 attempt to index global 'ly' (a boolean value)
stack traceback:
	[\directlua]:1: in main chunk.
l.85 }
    
? 
```

It's the same with `\begin{lilypond}`.

The `test.tex` file surprisingly compiles fine, I have no idea why.

**Comment by jperon** [comment] 2018-02-19 20:45
That's weird, I couldn't reproduce it. Should be fixed anyway.

**Closed by jperon** 2018-02-19 20:45 UTC
Labels: bug
